# Generated by Django 5.2.6 on 2026-04-02 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_car'),
        ('payments', '0004_payment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cars.car'),
        ),
    ]
