# Generated by Django 6.0.3 on 2026-03-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cashback_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
