# Generated by Django 5.2.6 on 2026-04-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_chat',
            field=models.BooleanField(default=False),
        ),
    ]
