# Generated by Django 5.2.6 on 2026-05-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
