# Generated by Django 5.2.6 on 2026-05-12 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_user_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_number',
        ),
    ]
