# Generated by Django 5.2.6 on 2026-05-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('engine', 'Motor'), ('electric', 'Elektrika'), ('body', 'Kuzov'), ('suspension', 'Podveska'), ('brake', 'Tormoz'), ('other', 'Boshqa')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
