# Generated by Django 5.2.6 on 2026-05-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_category_alter_product_price_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('engine', 'Motor'), ('electric', 'Elektrika'), ('body', 'Kuzov'), ('suspension', 'Podveska'), ('brake', 'Tormoz'), ('oil', 'Moy va filtrlar'), ('other', 'Boshqa')], default='other', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
