# Generated by Django 5.2.6 on 2026-05-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_product_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('engine', 'Motor Xadavoy'), ('electric', 'Elektrika'), ('body', 'Kuzov'), ('suspension', 'Podveska'), ('brake', 'Tormoz'), ('oil', 'Moy va filtrlar'), ('kuzuf', 'Kuzuf'), ('accessory', 'Avto bezak'), ('aralash', 'Aralash'), ('other', 'Boshqa')], default='other', max_length=20),
        ),
    ]
