# Generated by Django 5.2.6 on 2026-04-02 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='cars.car'),
        ),
    ]
