# Generated by Django 5.2.6 on 2026-04-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car',
        ),
    ]
