# Generated by Django 5.2.6 on 2026-05-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='plate_number',
            new_name='moshina_raqami',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='year',
            new_name='moshina_yili',
        ),
    ]
