# Generated by Django 5.2.6 on 2026-05-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_plate_number_car_moshina_raqami_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='moshina_raqami',
            new_name='plate_number',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='moshina_yili',
            new_name='year',
        ),
    ]
